server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true
    username: root
    password: Password123!@#
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true

security:
  jwt:
    secret-key: e3v7R0dInm7k2wtV3ZG3WT7boHmcZc4l8tB+odtfv34=
    expiration-time: 86400000  # 1 day in milliseconds

logging:
  level:
    shops.example.shops.auth.service.JwtService: DEBUG
